Merge in 73314, 73315 (<rdar://problem/6952287>):
------------------------------------------------------------------------
r73314 | lattner | 2009-06-13 17:07:48 -0700 (Sat, 13 Jun 2009) | 3 lines

improve localizability by not passing english phrases into 
diagnostics in some cases.

------------------------------------------------------------------------

------------------------------------------------------------------------
r73315 | lattner | 2009-06-13 17:23:56 -0700 (Sat, 13 Jun 2009) | 17 lines

change ParseStatementOrDeclaration to emit the 'missing ;' with
ExpectAndConsume instead of custom diag logic.  This gets us an
insertion hint and positions the ; at the end of the line 
instead of on the next token.  Before:

t.c:5:1: error: expected ';' after return statement
}
^

after:

t.c:4:11: error: expected ';' after return statement
  return 4
          ^
          ;


------------------------------------------------------------------------

llvm-svn=73490