Include the filename being looked up in an error message.  This gives us stuff like this: t3.c:5:10: error: 'vers2.h' file not found #include xstr(INCFILE(2).h)          ^
instead of:

t3.c:5:10: error: file not found
#include xstr(INCFILE(2).h)
         ^

which is useful if the #include name is generated through macro expansion.

llvm-svn=39398